### PR TITLE
:tada: Release 0.8.0

### PR DESCRIPTION
**Pull request by DJWassink**
Been a while since NPM got updated, pretty please netto? *puppy eyes*

### CODE REVIEW

**Comment by DJWassink** [comment]
Ooh I also added Node 8 to the travis.yml, seems to be going good 💪

**Comment by DJWassink** [comment]
psst @nettofarah wasup? 😆

**Comment by nettofarah** [comment]
💥 Done!
Sorry about the delay 😅

**Comment by DJWassink** [comment]
Haha no probs!  :tada:

**Pull request merged**
